### ISSUE TITLE
Urgent: What's the license?

### ISSUE THREAD

**Issue by sscarduzio** [incorelabs/chat-head-css#1]
Under what license is this software released? Apache 2.0 or MIT would be ideal.

Thank you for publishing this :)

**Comment by incorelabs** [comment]
Hi @sscarduzio this is MIT licensed. I haven't had the time to update it.

**Comment by incorelabs** [comment]
Have updated the license information.

**Comment by sscarduzio** [comment]
Thank you @incorelabs !!
